spring:
  datasource:
    url: jdbc:mysql://192.168.1.101:3306/demo1db
    username: root
    password: s3cret
  jpa:
    show-sql: true
    hibernate:
      ddl-auto: update
    properties:
      hibernate:
        dialect: org.hibernate.dialect.MySQL8Dialect

application:
  title: JPA MySQL Demo
  version: 1.0-SNAPSHOT
